### ISSUE TITLE
ImportError: No module named tldextract

### ISSUE THREAD

**Issue by LOSTtokens** [bit4woo/teemo#9]
Traceback (most recent call last):
  File "teemo.py", line 46, in <module>
    from domainsites.CrtSearch import CrtSearch
  File "/root/wangzhan/teemo/domainsites/CrtSearch.py", line 13, in <module>
    import tldextract
ImportError: No module named tldextract
Exception KeyError: KeyError(140336751116688,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by bit4woo** [comment]
python uninstall tldextract
pip install tldextract
